dist: trusty
cache:
  - apt
  - pip

install:
  - sudo apt-get install graphviz debhelper python3-all python3-setuptoolspython3-pip python3-requests

script:
  - export PATH=/usr/bin:${PATH}
  - sudo -H pip3 install -r requirements.dev.txt
  - ./devtools/statuses.py --commit=${TRAVIS_COMMIT} --build-id=${TRAVIS_BUILD_ID} --token=${token} --pull-id=${TRAVIS_PULL_REQUEST}
  - ./devtools/coverage.sh
  - dpkg-buildpackage -uc -us

after_success:
  - coveralls
